# Избавление от Nan значений

In [29]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
import matplotlib as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import roc_auc_score, roc_curve

In [123]:
test_2.shape, train_2.shape

((4277, 13), (8693, 14))

In [147]:
train_2 = pd.read_csv('train.csv')

In [148]:
train_2['HomePlanet'] = train_2['HomePlanet'].fillna('Not stated')
train_2['CryoSleep'] = train_2['CryoSleep'].fillna('Not stated')
train_2['Cabin'] = train_2['Cabin'].fillna('Not stated')
train_2['Destination'] = train_2['Destination'].fillna('Not stated')
train_2['VIP'] = train_2['VIP'].fillna('Not stated')
train_2['Name'] = train_2['Name'].fillna('Not stated')

In [149]:
train_2['Age'] = train_2['Age'].fillna(0)
train_2['RoomService'] = train_2['RoomService'].fillna(0)
train_2['FoodCourt'] = train_2['FoodCourt'].fillna(0)
train_2['ShoppingMall'] = train_2['ShoppingMall'].fillna(0)
train_2['Spa'] = train_2['Spa'].fillna(0)
train_2['VRDeck'] = train_2['VRDeck'].fillna(0)

In [159]:
test_2 = pd.read_csv('test.csv')

In [160]:
test_2['HomePlanet'] = test_2['HomePlanet'].fillna('Not stated')
test_2['CryoSleep'] = test_2['CryoSleep'].fillna('Not stated')
test_2['Cabin'] = test_2['Cabin'].fillna('Not stated')
test_2['Destination'] = test_2['Destination'].fillna('Not stated')
test_2['VIP'] = test_2['VIP'].fillna('Not stated')
test_2['Name'] = test_2['Name'].fillna('Not stated')

In [161]:
test_2['Age'] = test_2['Age'].fillna(0)
test_2['RoomService'] = test_2['RoomService'].fillna(0)
test_2['FoodCourt'] = test_2['FoodCourt'].fillna(0)
test_2['ShoppingMall'] = test_2['ShoppingMall'].fillna(0)
test_2['Spa'] = test_2['Spa'].fillna(0)
test_2['VRDeck'] = test_2['VRDeck'].fillna(0)

In [150]:
train_2.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

In [162]:
numeric_indices = np.array([5, 7, 8, 9, 10, 11])
categorical_indices = np.array([0, 1, 2, 3, 4, 6, 12])

# Проверка на Nan значения

In [129]:
l = []
for val in test_2['Spa']:
    l.append(val == val)
l.count(False)

0

# Модель catboost

In [69]:
import catboost

In [ ]:
X_train = train_2.iloc[:, :-1]
Y_train = train_2['Transported']
X_test = test_2

In [164]:
boosting_model = catboost.CatBoostClassifier(n_estimators=200, 
                                             cat_features=categorical_indices)

boosting_model.fit(X_train, Y_train)

y_train_predicted = boosting_model.predict(X_train)
y_test_predicted = boosting_model.predict(X_test)

Learning rate set to 0.113479
0:	learn: 0.6435691	total: 39.6ms	remaining: 7.88s
1:	learn: 0.6056222	total: 85.6ms	remaining: 8.48s
2:	learn: 0.5754640	total: 132ms	remaining: 8.68s
3:	learn: 0.5469972	total: 175ms	remaining: 8.55s
4:	learn: 0.5288494	total: 217ms	remaining: 8.47s
5:	learn: 0.5143853	total: 261ms	remaining: 8.43s
6:	learn: 0.5010363	total: 297ms	remaining: 8.2s
7:	learn: 0.4914111	total: 334ms	remaining: 8.02s
8:	learn: 0.4845957	total: 372ms	remaining: 7.89s
9:	learn: 0.4772362	total: 414ms	remaining: 7.86s
10:	learn: 0.4710832	total: 451ms	remaining: 7.75s
11:	learn: 0.4682920	total: 487ms	remaining: 7.63s
12:	learn: 0.4629786	total: 523ms	remaining: 7.53s
13:	learn: 0.4599847	total: 562ms	remaining: 7.47s
14:	learn: 0.4553194	total: 599ms	remaining: 7.38s
15:	learn: 0.4527019	total: 639ms	remaining: 7.34s
16:	learn: 0.4502288	total: 682ms	remaining: 7.34s
17:	learn: 0.4491798	total: 707ms	remaining: 7.14s
18:	learn: 0.4477343	total: 732ms	remaining: 6.98s
19:	learn: 0.4455443	total: 771ms	remaining: 6.94s
20:	learn: 0.4446991	total: 808ms	remaining: 6.89s
21:	learn: 0.4422018	total: 848ms	remaining: 6.86s
22:	learn: 0.4409899	total: 889ms	remaining: 6.84s
23:	learn: 0.4388197	total: 928ms	remaining: 6.8s
24:	learn: 0.4371892	total: 966ms	remaining: 6.76s
25:	learn: 0.4358930	total: 1.01s	remaining: 6.73s
26:	learn: 0.4353156	total: 1.04s	remaining: 6.68s
27:	learn: 0.4347075	total: 1.07s	remaining: 6.55s
28:	learn: 0.4334279	total: 1.1s	remaining: 6.52s
29:	learn: 0.4329022	total: 1.14s	remaining: 6.44s
30:	learn: 0.4321584	total: 1.17s	remaining: 6.39s
31:	learn: 0.4308587	total: 1.21s	remaining: 6.36s
32:	learn: 0.4301769	total: 1.25s	remaining: 6.3s
33:	learn: 0.4293712	total: 1.28s	remaining: 6.27s
34:	learn: 0.4284998	total: 1.32s	remaining: 6.24s
35:	learn: 0.4270753	total: 1.36s	remaining: 6.21s
36:	learn: 0.4260911	total: 1.4s	remaining: 6.17s
37:	learn: 0.4256297	total: 1.44s	remaining: 6.12s
38:	learn: 0.4251348	total: 1.48s	remaining: 6.09s
39:	learn: 0.4245189	total: 1.51s	remaining: 6.06s
40:	learn: 0.4239074	total: 1.55s	remaining: 6.01s
41:	learn: 0.4233356	total: 1.58s	remaining: 5.96s
42:	learn: 0.4226961	total: 1.62s	remaining: 5.92s
43:	learn: 0.4223070	total: 1.65s	remaining: 5.86s
44:	learn: 0.4221371	total: 1.68s	remaining: 5.78s
45:	learn: 0.4220567	total: 1.69s	remaining: 5.67s
46:	learn: 0.4215051	total: 1.73s	remaining: 5.63s
47:	learn: 0.4212697	total: 1.76s	remaining: 5.58s
48:	learn: 0.4211222	total: 1.8s	remaining: 5.55s
49:	learn: 0.4209176	total: 1.83s	remaining: 5.51s
50:	learn: 0.4206183	total: 1.87s	remaining: 5.47s
51:	learn: 0.4202232	total: 1.91s	remaining: 5.42s
52:	learn: 0.4194351	total: 1.94s	remaining: 5.38s
53:	learn: 0.4189173	total: 1.98s	remaining: 5.35s
54:	learn: 0.4184280	total: 2.02s	remaining: 5.32s
55:	learn: 0.4180477	total: 2.05s	remaining: 5.28s
56:	learn: 0.4175066	total: 2.09s	remaining: 5.24s
57:	learn: 0.4172031	total: 2.12s	remaining: 5.2s
58:	learn: 0.4168884	total: 2.16s	remaining: 5.16s
59:	learn: 0.4163745	total: 2.19s	remaining: 5.12s
60:	learn: 0.4158989	total: 2.23s	remaining: 5.08s
61:	learn: 0.4156992	total: 2.26s	remaining: 5.04s
62:	learn: 0.4154383	total: 2.3s	remaining: 4.99s
63:	learn: 0.4152321	total: 2.33s	remaining: 4.96s
64:	learn: 0.4148397	total: 2.37s	remaining: 4.92s
65:	learn: 0.4146568	total: 2.41s	remaining: 4.89s
66:	learn: 0.4145268	total: 2.44s	remaining: 4.85s
67:	learn: 0.4142089	total: 2.48s	remaining: 4.82s
68:	learn: 0.4136452	total: 2.52s	remaining: 4.78s
69:	learn: 0.4130010	total: 2.55s	remaining: 4.74s
70:	learn: 0.4128103	total: 2.59s	remaining: 4.71s
71:	learn: 0.4125360	total: 2.63s	remaining: 4.67s
72:	learn: 0.4117911	total: 2.67s	remaining: 4.64s
73:	learn: 0.4113013	total: 2.7s	remaining: 4.6s
74:	learn: 0.4109887	total: 2.74s	remaining: 4.57s
75:	learn: 0.4104288	total: 2.77s	remaining: 4.53s
76:	learn: 0.4097452	total: 2.81s	remaining: 4.49s
77:	learn: 0.4096121	total: 2.85s	remaining: 4.46s
78:	learn: 0.4091494	total: 2.89s	remaining: 4.42s
79:	learn: 0.4089153	total: 2.92s	remaining: 4.38s
80:	learn: 0.4085480	total: 2.95s	remaining: 4.34s
81:	learn: 0.4082857	total: 2.99s	remaining: 4.3s
82:	learn: 0.4078907	total: 3.02s	remaining: 4.26s
83:	learn: 0.4074685	total: 3.07s	remaining: 4.24s
84:	learn: 0.4072025	total: 3.1s	remaining: 4.2s
85:	learn: 0.4070621	total: 3.14s	remaining: 4.16s
86:	learn: 0.4068675	total: 3.17s	remaining: 4.12s
87:	learn: 0.4068653	total: 3.2s	remaining: 4.07s
88:	learn: 0.4065000	total: 3.24s	remaining: 4.04s
89:	learn: 0.4063292	total: 3.28s	remaining: 4.01s
90:	learn: 0.4061385	total: 3.31s	remaining: 3.97s
91:	learn: 0.4059755	total: 3.35s	remaining: 3.94s
92:	learn: 0.4058549	total: 3.39s	remaining: 3.9s
93:	learn: 0.4056123	total: 3.43s	remaining: 3.87s
94:	learn: 0.4054318	total: 3.47s	remaining: 3.83s
95:	learn: 0.4052657	total: 3.5s	remaining: 3.8s
96:	learn: 0.4049255	total: 3.54s	remaining: 3.76s
97:	learn: 0.4048654	total: 3.58s	remaining: 3.73s
98:	learn: 0.4042654	total: 3.62s	remaining: 3.69s
99:	learn: 0.4038320	total: 3.65s	remaining: 3.65s
100:	learn: 0.4029958	total: 3.69s	remaining: 3.62s
101:	learn: 0.4025092	total: 3.73s	remaining: 3.58s
102:	learn: 0.4024182	total: 3.77s	remaining: 3.55s
103:	learn: 0.4016525	total: 3.8s	remaining: 3.51s
104:	learn: 0.4009396	total: 3.84s	remaining: 3.48s
105:	learn: 0.4008153	total: 3.88s	remaining: 3.44s
106:	learn: 0.4006163	total: 3.91s	remaining: 3.4s
107:	learn: 0.4003052	total: 3.95s	remaining: 3.37s
108:	learn: 0.4001226	total: 3.98s	remaining: 3.33s
109:	learn: 0.3997017	total: 4.02s	remaining: 3.29s
110:	learn: 0.3994987	total: 4.05s	remaining: 3.25s
111:	learn: 0.3992497	total: 4.09s	remaining: 3.21s
112:	learn: 0.3992018	total: 4.13s	remaining: 3.18s
113:	learn: 0.3990526	total: 4.17s	remaining: 3.14s
114:	learn: 0.3988069	total: 4.2s	remaining: 3.11s
115:	learn: 0.3986761	total: 4.24s	remaining: 3.07s
116:	learn: 0.3983618	total: 4.28s	remaining: 3.03s
117:	learn: 0.3981422	total: 4.31s	remaining: 3s
118:	learn: 0.3978412	total: 4.35s	remaining: 2.96s
119:	learn: 0.3976335	total: 4.39s	remaining: 2.92s
120:	learn: 0.3973827	total: 4.42s	remaining: 2.89s
121:	learn: 0.3969787	total: 4.46s	remaining: 2.85s
122:	learn: 0.3966170	total: 4.5s	remaining: 2.81s
123:	learn: 0.3960769	total: 4.53s	remaining: 2.78s
124:	learn: 0.3958788	total: 4.57s	remaining: 2.74s
125:	learn: 0.3955304	total: 4.6s	remaining: 2.7s
126:	learn: 0.3952361	total: 4.64s	remaining: 2.67s
127:	learn: 0.3948833	total: 4.68s	remaining: 2.63s
128:	learn: 0.3947514	total: 4.71s	remaining: 2.6s
129:	learn: 0.3946477	total: 4.75s	remaining: 2.56s
130:	learn: 0.3944743	total: 4.79s	remaining: 2.52s
131:	learn: 0.3940395	total: 4.83s	remaining: 2.49s
132:	learn: 0.3936694	total: 4.87s	remaining: 2.45s
133:	learn: 0.3934528	total: 4.9s	remaining: 2.42s
134:	learn: 0.3933076	total: 4.94s	remaining: 2.38s
135:	learn: 0.3932073	total: 4.97s	remaining: 2.34s
136:	learn: 0.3930065	total: 5.01s	remaining: 2.3s
137:	learn: 0.3928834	total: 5.04s	remaining: 2.27s
138:	learn: 0.3925780	total: 5.08s	remaining: 2.23s
139:	learn: 0.3923564	total: 5.12s	remaining: 2.19s
140:	learn: 0.3921238	total: 5.16s	remaining: 2.16s
141:	learn: 0.3919714	total: 5.19s	remaining: 2.12s
142:	learn: 0.3916479	total: 5.22s	remaining: 2.08s
143:	learn: 0.3916024	total: 5.26s	remaining: 2.04s
144:	learn: 0.3911888	total: 5.3s	remaining: 2.01s
145:	learn: 0.3908668	total: 5.34s	remaining: 1.97s
146:	learn: 0.3905609	total: 5.38s	remaining: 1.94s
147:	learn: 0.3905275	total: 5.41s	remaining: 1.9s
148:	learn: 0.3904799	total: 5.44s	remaining: 1.86s
149:	learn: 0.3903746	total: 5.48s	remaining: 1.83s
150:	learn: 0.3900034	total: 5.51s	remaining: 1.79s
151:	learn: 0.3899895	total: 5.55s	remaining: 1.75s
152:	learn: 0.3899547	total: 5.59s	remaining: 1.72s
153:	learn: 0.3897879	total: 5.63s	remaining: 1.68s
154:	learn: 0.3897240	total: 5.66s	remaining: 1.64s
155:	learn: 0.3896096	total: 5.7s	remaining: 1.61s
156:	learn: 0.3889771	total: 5.73s	remaining: 1.57s
157:	learn: 0.3888068	total: 5.77s	remaining: 1.53s
158:	learn: 0.3887405	total: 5.81s	remaining: 1.5s
159:	learn: 0.3886036	total: 5.85s	remaining: 1.46s
160:	learn: 0.3884549	total: 5.89s	remaining: 1.43s

161:	learn: 0.3879702	total: 5.92s	remaining: 1.39s
162:	learn: 0.3877257	total: 5.96s	remaining: 1.35s
163:	learn: 0.3876167	total: 6s	remaining: 1.32s
164:	learn: 0.3874925	total: 6.03s	remaining: 1.28s
165:	learn: 0.3873370	total: 6.07s	remaining: 1.24s
166:	learn: 0.3871412	total: 6.1s	remaining: 1.21s
167:	learn: 0.3867488	total: 6.14s	remaining: 1.17s
168:	learn: 0.3866666	total: 6.18s	remaining: 1.13s
169:	learn: 0.3865643	total: 6.21s	remaining: 1.1s
170:	learn: 0.3861122	total: 6.25s	remaining: 1.06s
171:	learn: 0.3859176	total: 6.29s	remaining: 1.02s
172:	learn: 0.3858713	total: 6.32s	remaining: 987ms
173:	learn: 0.3856974	total: 6.36s	remaining: 950ms
174:	learn: 0.3855203	total: 6.39s	remaining: 914ms
175:	learn: 0.3853858	total: 6.43s	remaining: 877ms
176:	learn: 0.3851532	total: 6.48s	remaining: 842ms
177:	learn: 0.3849822	total: 6.51s	remaining: 805ms
178:	learn: 0.3844936	total: 6.55s	remaining: 768ms
179:	learn: 0.3843829	total: 6.58s	remaining: 732ms
180:	learn: 0.3843124	total: 6.62s	remaining: 695ms
181:	learn: 0.3838245	total: 6.66s	remaining: 658ms
182:	learn: 0.3836032	total: 6.69s	remaining: 622ms
183:	learn: 0.3831584	total: 6.73s	remaining: 585ms
184:	learn: 0.3828921	total: 6.76s	remaining: 549ms
185:	learn: 0.3827455	total: 6.8s	remaining: 512ms
186:	learn: 0.3822906	total: 6.84s	remaining: 476ms
187:	learn: 0.3822092	total: 6.9s	remaining: 441ms
188:	learn: 0.3818013	total: 6.95s	remaining: 404ms
189:	learn: 0.3815178	total: 6.99s	remaining: 368ms
190:	learn: 0.3813751	total: 7.03s	remaining: 331ms
191:	learn: 0.3807424	total: 7.07s	remaining: 295ms
192:	learn: 0.3804616	total: 7.11s	remaining: 258ms
193:	learn: 0.3802903	total: 7.14s	remaining: 221ms
194:	learn: 0.3800898	total: 7.18s	remaining: 184ms
195:	learn: 0.3797050	total: 7.22s	remaining: 147ms
196:	learn: 0.3794090	total: 7.26s	remaining: 111ms
197:	learn: 0.3790932	total: 7.3s	remaining: 73.7ms
198:	learn: 0.3788923	total: 7.34s	remaining: 36.9ms
199:	learn: 0.3788401	total: 7.37s	remaining: 0us

# Получение финального csv файла

In [165]:
test_2['Transported'] = pd.Series(y_test_predicted)

In [166]:
test_2

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0013_01,Earth,True,G/3/S,TRAPPIST-1e,27.0,False,0.0,0.0,0.0,0.0,0.0,Nelly Carsoning,True
1,0018_01,Earth,False,F/4/S,TRAPPIST-1e,19.0,False,0.0,9.0,0.0,2823.0,0.0,Lerome Peckers,False
2,0019_01,Europa,True,C/0/S,55 Cancri e,31.0,False,0.0,0.0,0.0,0.0,0.0,Sabih Unhearfus,True
3,0021_01,Europa,False,C/1/S,TRAPPIST-1e,38.0,False,0.0,6652.0,0.0,181.0,585.0,Meratz Caltilter,True
4,0023_01,Earth,False,F/5/S,TRAPPIST-1e,20.0,False,10.0,0.0,635.0,0.0,0.0,Brence Harperez,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4272,9266_02,Earth,True,G/1496/S,TRAPPIST-1e,34.0,False,0.0,0.0,0.0,0.0,0.0,Jeron Peter,True
4273,9269_01,Earth,False,Not stated,TRAPPIST-1e,42.0,False,0.0,847.0,17.0,10.0,144.0,Matty Scheron,False
4274,9271_01,Mars,True,D/296/P,55 Cancri e,0.0,False,0.0,0.0,0.0,0.0,0.0,Jayrin Pore,True
4275,9273_01,Europa,False,D/297/P,Not stated,0.0,False,0.0,2680.0,0.0,0.0,523.0,Kitakan Conale,True
4276,9277_01,Earth,True,G/1498/S,PSO J318.5-22,43.0,False,0.0,0.0,0.0,0.0,0.0,Lilace Leonzaley,True

In [167]:
final_df = test_2[['PassengerId', 'Transported']]

In [168]:
final_df

     PassengerId Transported
0        0013_01        True
1        0018_01       False
2        0019_01        True
3        0021_01        True
4        0023_01        True
...          ...         ...
4272     9266_02        True
4273     9269_01       False
4274     9271_01        True
4275     9273_01        True
4276     9277_01        True

[4277 rows x 2 columns]

In [169]:
final_df.to_csv('Submission_13.csv') #0.80